/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortionIndexRouteImport } from './routes/portion/index'
import { Route as PortionUpdateRouteImport } from './routes/portion/update'
import { Route as PortionListRouteImport } from './routes/portion/list'
import { Route as PortionCreateRouteImport } from './routes/portion/create'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionIndexRoute = PortionIndexRouteImport.update({
  id: '/portion/',
  path: '/portion/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionUpdateRoute = PortionUpdateRouteImport.update({
  id: '/portion/update',
  path: '/portion/update',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionListRoute = PortionListRouteImport.update({
  id: '/portion/list',
  path: '/portion/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionCreateRoute = PortionCreateRouteImport.update({
  id: '/portion/create',
  path: '/portion/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/planner': typeof PlannerRoute
  '/portion/create': typeof PortionCreateRoute
  '/portion/list': typeof PortionListRoute
  '/portion/update': typeof PortionUpdateRoute
  '/portion/': typeof PortionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/planner': typeof PlannerRoute
  '/portion/create': typeof PortionCreateRoute
  '/portion/list': typeof PortionListRoute
  '/portion/update': typeof PortionUpdateRoute
  '/portion': typeof PortionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/planner': typeof PlannerRoute
  '/portion/create': typeof PortionCreateRoute
  '/portion/list': typeof PortionListRoute
  '/portion/update': typeof PortionUpdateRoute
  '/portion/': typeof PortionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meals'
    | '/planner'
    | '/portion/create'
    | '/portion/list'
    | '/portion/update'
    | '/portion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meals'
    | '/planner'
    | '/portion/create'
    | '/portion/list'
    | '/portion/update'
    | '/portion'
  id:
    | '__root__'
    | '/'
    | '/meals'
    | '/planner'
    | '/portion/create'
    | '/portion/list'
    | '/portion/update'
    | '/portion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealsRoute: typeof MealsRoute
  PlannerRoute: typeof PlannerRoute
  PortionCreateRoute: typeof PortionCreateRoute
  PortionListRoute: typeof PortionListRoute
  PortionUpdateRoute: typeof PortionUpdateRoute
  PortionIndexRoute: typeof PortionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portion/': {
      id: '/portion/'
      path: '/portion'
      fullPath: '/portion/'
      preLoaderRoute: typeof PortionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portion/update': {
      id: '/portion/update'
      path: '/portion/update'
      fullPath: '/portion/update'
      preLoaderRoute: typeof PortionUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portion/list': {
      id: '/portion/list'
      path: '/portion/list'
      fullPath: '/portion/list'
      preLoaderRoute: typeof PortionListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portion/create': {
      id: '/portion/create'
      path: '/portion/create'
      fullPath: '/portion/create'
      preLoaderRoute: typeof PortionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealsRoute: MealsRoute,
  PlannerRoute: PlannerRoute,
  PortionCreateRoute: PortionCreateRoute,
  PortionListRoute: PortionListRoute,
  PortionUpdateRoute: PortionUpdateRoute,
  PortionIndexRoute: PortionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
