/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortionsIndexRouteImport } from './routes/portions/index'
import { Route as PortionsCreateRouteImport } from './routes/portions/create'
import { Route as PortionsPortionIdEditRouteImport } from './routes/portions/$portionId/edit'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionsIndexRoute = PortionsIndexRouteImport.update({
  id: '/portions/',
  path: '/portions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionsCreateRoute = PortionsCreateRouteImport.update({
  id: '/portions/create',
  path: '/portions/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PortionsPortionIdEditRoute = PortionsPortionIdEditRouteImport.update({
  id: '/portions/$portionId/edit',
  path: '/portions/$portionId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/planner': typeof PlannerRoute
  '/portions/create': typeof PortionsCreateRoute
  '/portions/': typeof PortionsIndexRoute
  '/portions/$portionId/edit': typeof PortionsPortionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/planner': typeof PlannerRoute
  '/portions/create': typeof PortionsCreateRoute
  '/portions': typeof PortionsIndexRoute
  '/portions/$portionId/edit': typeof PortionsPortionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/planner': typeof PlannerRoute
  '/portions/create': typeof PortionsCreateRoute
  '/portions/': typeof PortionsIndexRoute
  '/portions/$portionId/edit': typeof PortionsPortionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/meals'
    | '/planner'
    | '/portions/create'
    | '/portions/'
    | '/portions/$portionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meals'
    | '/planner'
    | '/portions/create'
    | '/portions'
    | '/portions/$portionId/edit'
  id:
    | '__root__'
    | '/'
    | '/meals'
    | '/planner'
    | '/portions/create'
    | '/portions/'
    | '/portions/$portionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealsRoute: typeof MealsRoute
  PlannerRoute: typeof PlannerRoute
  PortionsCreateRoute: typeof PortionsCreateRoute
  PortionsIndexRoute: typeof PortionsIndexRoute
  PortionsPortionIdEditRoute: typeof PortionsPortionIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portions/': {
      id: '/portions/'
      path: '/portions'
      fullPath: '/portions/'
      preLoaderRoute: typeof PortionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portions/create': {
      id: '/portions/create'
      path: '/portions/create'
      fullPath: '/portions/create'
      preLoaderRoute: typeof PortionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portions/$portionId/edit': {
      id: '/portions/$portionId/edit'
      path: '/portions/$portionId/edit'
      fullPath: '/portions/$portionId/edit'
      preLoaderRoute: typeof PortionsPortionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealsRoute: MealsRoute,
  PlannerRoute: PlannerRoute,
  PortionsCreateRoute: PortionsCreateRoute,
  PortionsIndexRoute: PortionsIndexRoute,
  PortionsPortionIdEditRoute: PortionsPortionIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
